# Generated by Django 3.1.1 on 2020-11-15 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useradmin', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_date', models.DateField(auto_now_add=True)),
                ('exp_date', models.DateField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('sold', models.IntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.medicine')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
            options={
                'db_table': 'shop_stock',
            },
        ),
    ]
